### ISSUE TITLE
code in directory s32x/httpclient expects import "s32x.com/httpclient"

### ISSUE THREAD

**Issue by selimonline** [s32x/httpclient#1]
I am having this issues : 
code in directory s32x/httpclient expects import "s32x.com/httpclient"

If I import, it says impot but not used. ???

nothing makes sense...

**Comment by amaurymartiny** [comment]
How didi you solve it?

**Comment by s32x** [comment]
@amaurymartiny If you're having this problem you should be able to use `github.com/s32x/httpclient`. I've removed the requirement to use the s32x.com domain
