### ISSUE TITLE
Latest changes breaks backward-compat, e.g. with trumail

### ISSUE THREAD

**Issue by amaury1093** [s32x/httpclient#2]
```
go install github.com/sdwolfe32/trumail
# github.com/sdwolfe32/trumail
src/github.com/sdwolfe32/trumail/main.go:44:13: undefined: httpclient.GetString
```

**Comment by s32x** [comment]
There is a lock file in that project. You'll need to retrieve the glide dependencies before installing. go installing doesn't and shouldn't be the way you install it. Otherwise, I encourage you to get in contact with email-checker since they are the ones that own the project now.
